config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root "users#index"

  get "/users/:id/profile", to: "users#show", as: "user"
  get "/users", to: "users#index", as: "users"
  
  post "/users/:user_id/posts/:id/newcomment", to: "comments#create", as: "create_new_comment"
  post "/users/:user_id/posts/:id/newlike", to: "likes#create", as: "create_new_like"
  get "/users/:user_id/posts/new", to: "posts#new", as: "user_new_posts"
  post "/users/:user_id/posts/new", to: "posts#create", as: "create_user_posts"
  get "/users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  get "/users/:user_id/posts", to: "posts#index", as: "user_posts"

  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  delete "/users/:user_id/posts/:post_id/comments/:id", to: "comments#destroy", as: "delete_comment"
  delete "/users/:user_id/posts/:id", to: "posts#destroy", as: "delete_post"

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= current_user

    if user.role == 'Admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_posts_counter

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  private

  def update_posts_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: @comments
  end

  def create
    @post = current_user.posts.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :name, :photo, :bio, :password, :password_confirmation, :role)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :name, :photo, :bio, :password, :current_password, :password_confirmation, :role)
    end
  end

  def after_sending_reset_password_instructions_path_for(resource_name)
    new_session_path(resource_name) if is_navigational_format?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @post = Post.find(params[:id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    return unless @comment.save

    redirect_to user_post_path(params[:user_id], params[:id]), notice: 'Comment was successfully added.'
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    @post.decrement!(:comment_counter)
    @comment.destroy
    redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:id])
    @like = Like.create(user: current_user, post: @post)

    if @like.persisted?
      flash[:success] = 'Liked successfully!'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :post, through: :user

  before_action :set_user, only: %i[index show]
  before_action :set_post, only: %i[show destroy]

  def index
    @posts = @user.posts
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def destroy
    @author = @post.author
    @author.decrement!(:post_counter)
    @post.destroy!
    redirect_to user_posts_path(params[:user_id]), notice: 'Post was successfully deleted.'
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_posts_path(current_user)

    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end

  def sign_out_user
    sign_out current_user
    redirect_to root_path
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemstone Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </header>

  <body class="body-container">
    <%= yield %>
  </body>
</html>

app/views/posts/_comment_card.html.erb
<div class="comment-container flex-col gap-1">
    <% if comments.any? %>
        <% comments.includes(:user).each do |comment| %>
            <div class="flex justify-between">
                <div class="comment-card">
                    <div class="comment-name" ><%= comment.user.name %></div>
                    <div ><%= comment.text %></div>
                </div>
                <% if @post && comment && can?(:destroy, comment) %>
                    <%= button_to "Delete", delete_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <div>No comment</div>
    <% end %>
</div>

app/views/posts/_post_card.html.erb
<a class="user-card gap-0-5 flex-col items-start border-card" href="<%= user_post_path(user_id: post.author_id, id: post.id) %>">
    <div class="flex justify-between w-full items-center">
        <span class="card-title"><%= post.title %></span>
         <% if post && can?(:destroy, post) %>
            <%= button_to "Delete", delete_post_path(user_id: @user.id, id: post.id), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
    </div>
    <span class="user-bio line-clamp-2" style="max-width: 60ch"><%= post.text %></span>
    <span class="user-totalpost w-full">Comments : <%= post.comment_counter %>, Likes : <%= post.like_counter %></span>
            <% if comments.present? %>
                <% if comments.any? %>
                    <%= render partial: "comment_card", locals: {comments: comments} %>
                <% else %>
                    <div class="comment-container">
                        <div>No comment</div>
                    </div>
                <% end %>
            <% end %>
</a>

app/views/posts/index.html.erb
<div class="container">
    <%= render partial: "users/user_headline" %>
    <%= render partial: "users/user", locals: {user: @user }%>
    <% @posts.includes(:author,comments: :user).each do |post| %>
        <%= render partial: "post_card", locals: { post: post, comments: post.recent_comments } %>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_with model: @post, url: create_user_posts_path ,class: "user-card border-card flex-col items-start gap-1" do |form| %>
      <%= form.label :title, "Title of the post :" %>
      <%= form.text_field :title %>
      <%= form.label :text, "Post text :" %>
      <%= form.text_area :text, size: "70x5" %>
      <div class="flex justify-center w-full">
        <%= form.submit "Add new post" %>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render partial: "users/user_headline" %>
<div class="container border-card p-4">
    <div class="flex-col items-center">
        <h1><%= @post.title %></h1>
        <span style="font-size: large; font-weight:300;">by <%= @user.name %></span>
        <span style="font-size: smaller; font-weight:100; margin-top: 10px">Comments : <%= @post.comment_counter %>, Likes : <%= @post.like_counter %></span>
    </div>

    <div class="post-text">
        <%= @post.text %>
    </div>

    <div class="comment-container">
        <%= form_with model: @comment, url: create_new_comment_path(user_id: @user.id, id: @post.id) ,class: "flex items-start gap-1" do |form| %>
            <%= form.text_area :text, size: "70x5" %>
            <%= form.submit "Add new comment" %>
        <% end %>
    </div>

    <div class="comment-container">
        <%= form_with model: @like, url: create_new_like_path(user_id: @user.id, id: @post.id) ,class: "flex items-start gap-1" do |form| %>
            <%= form.submit "Add likes comment", class: "w-full" %>
        <% end %>
    </div>

    <%= render partial: "comment_card", locals: {comments: @post.comments} %>
</div>

app/views/users/_user.html.erb
<a class="user-card border-card" href="<%= user_path(user) %>">
        <img src="<%= user.photo %>" class="user-photo">
        <div class="user-card-info">
            <div class="flex-col">
                <span class="card-title"><%= user.name %></span>
                <span class="user-bio"><%= user.bio %></span>
            </div>
            <span class="user-totalpost">Number of post : <%= user.post_counter %></span>
        </div>
</a>

app/views/users/_user_headline.html.erb
<div class="container w-full border-card p-4" style="margin-bottom:25px">
  <div class="w-full flex items-center " style="justify-content: space-between" >
  <div class="flex flex-col">
      <h1>
        Hi <%= current_user.name %>
      </h1>
      
      <% unless current_user.confirmed? %>
        <div class="border-card user-card justify-center " style="color:red;">Email not verified</div>
      <% end %>
  </div>
  <div class="flex flex-col">
    <div class="border-card user-card justify-center " style="text-transform: capitalize; margin-bottom:20px">
        Role: <%= current_user.role  %>
      </div>
    <%= link_to 'Sign Out', sign_out_user_path, class: "border-card user-card justify-center card-title", 
        style: "background-color:black; color:white; width: 100%;" %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
    <%= render partial: "user_headline" %>
    <%= render partial: "user", collection: @users %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <%= render partial: "user_headline" %>
  <%= render partial: "user", locals: { user: @user } %>

  <div class="gap-1" style="display:flex; justify-content: start; width:100%;">
    <div class="user-card gap-0 flex-col items-start border-card">
      <span class="card-title">Bio</span>
      <span class="user-bio"><%= @user.bio %></span>
    </div>
    <% if current_user == @user%>
      <a
        href="<%= user_new_posts_path(user_id: @user.id) %>" 
        class="border-card user-card justify-center card-title" 
        style="background-color:black; color:white;">
        Add New Post
      </a>
    <% end %>
  </div>

  <% if @recent_posts.any? %>
    <% @recent_posts.each do |recent_post| %>
      <%= render partial: "posts/post_card", locals: { post: recent_post, comments: nil } %>
    <% end %>

    <a 
      href="<%= user_posts_path(user_id: @user.id) %>" 
      class="user-card border-card" 
      style="width: fit-content;"
    > 
      Load all post  
    </a>
  <% else %>
    <p>No posts found.</p>
  <% end %>
</div>